item{
    id:1
    name: 'Adidas'
}
item{
    id:2
    name: 'Cocacola'
}
item{
    id:3
    name: 'Heineken'
}
item{
    id:4
    name: 'Nike'
}
item{
    id:5
    name: 'Pepsi'
}
item{
    id:6
    name: 'Puma'
}
item{
    id:7
    name: 'Sprite'
}
